@base=https://localhost:5001
 
### Create a new item
 
POST {{base}}/peoplespartnership/api/studioitem
Content-Type: application/json

{
  "Acquired": "2023-03-23T21:20:00Z",  
  "Name": "New Studio Item",
  "Description": "Description of the new item",
  "SerialNumber": "123456789",
  "Price": 149.99,
  "Eurorack": true,
  "StudioItemTypeId": 1  
}
### Get All items
 
GET {{base}}/peoplespartnership/api/studioitem/GetAll
Content-Type: application/json

### Get one 123
GET {{base}}/peoplespartnership/api/studioitem/1
Content-Type: application/json
### Update item
 
PUT {{base}}/peoplespartnership/api/studioitem
Content-Type: application/json

{
  "StudioItemId": 123,  
  "Acquired": "2023-04-01T00:00:00Z",  
  "Name": "Updated Studio Item",
  "Description": "Modified description",
  "SerialNumber": "987654321",
  "Price": 199.99,
  "Eurorack": false,
  "StudioItemTypeId": 2  
}

### Delete item
 
DELETE {{base}}/peoplespartnership/api/studioitem/3