// <auto-generated />
using System;
using AcmeStudios.ApiRefactor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeStudios.Migrations
{
    [DbContext(typeof(EFStudioDbContext))]
    [Migration("20240324164007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("AcmeStudios.ApiRefactor.Entities.StudioItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Acquired")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eurorack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Sold")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SoldFor")
                        .HasColumnType("TEXT");

                    b.Property<long>("StudioItemTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudioItemTypeId");

                    b.ToTable("StudioItems");
                });

            modelBuilder.Entity("AcmeStudios.ApiRefactor.Entities.StudioItemType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudioItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Value = "Synthesiser"
                        },
                        new
                        {
                            Id = 2L,
                            Value = "Drum Machine"
                        },
                        new
                        {
                            Id = 3L,
                            Value = "Effect"
                        },
                        new
                        {
                            Id = 4L,
                            Value = "Sequencer"
                        },
                        new
                        {
                            Id = 5L,
                            Value = "Mixer"
                        },
                        new
                        {
                            Id = 6L,
                            Value = "Oscillator"
                        },
                        new
                        {
                            Id = 7L,
                            Value = "Utility"
                        });
                });

            modelBuilder.Entity("AcmeStudios.ApiRefactor.Entities.StudioItem", b =>
                {
                    b.HasOne("AcmeStudios.ApiRefactor.Entities.StudioItemType", "StudioItemType")
                        .WithMany("StudioItem")
                        .HasForeignKey("StudioItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudioItemType");
                });

            modelBuilder.Entity("AcmeStudios.ApiRefactor.Entities.StudioItemType", b =>
                {
                    b.Navigation("StudioItem");
                });
#pragma warning restore 612, 618
        }
    }
}
